config/routes.rb
Rails.application.routes.draw do

	resources :home do
		collection do
			get :search_models
			get :search_model
			get :search_model_years
			get :search_vehicle_prices
		end
	end
  root to: 'home#index'
end

app/models/car_mark.rb
class CarMark < ActiveRecord::Base
	has_many :car_models
end

app/models/car_model.rb
class CarModel < ActiveRecord::Base
	belongs_to :car_mark
	has_many :car_model_years
end

app/models/car_model_year.rb
class CarModelYear < ActiveRecord::Base
  belongs_to :car_model
  has_many :vehicle_prices
end

app/models/vehicle_price.rb
class VehiclePrice < ActiveRecord::Base
  belongs_to :car_model_year
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :json_mark, if: :car_mark_empty?, only: :index
  before_action :json_model, if: :car_model_empty?, only: :search_models
  before_action :json_model_year, if: :car_model_year_empty?, only: :search_model_years
  before_action :json_vehicle_price, if: :vehicle_price_empty?, only: :search_vehicle_prices

  def index
    @car_marks = CarMark.where.not(fipe_id: nil).select("car_marks.fipe_id as id, car_marks.name as name")
  end

  def search_vehicle_prices
    if !params[:car_model][:fipe_id].blank? && !params[:car_mark][:fipe_id].blank? && !params[:car_model_year][:fipe_id].blank?
      car_mark = CarMark.find_by(fipe_id: params[:car_mark][:fipe_id])
      car_model = CarModel.find_by(fipe_id: params[:car_model][:fipe_id], car_mark: car_mark)
      car_model_year = CarModelYear.find_by(car_model: car_model, fipe_key: "#{params[:car_model_year][:fipe_id]}-1")
      @vehicle_prices = VehiclePrice.find_by(car_model_year: car_model_year)
      respond_to do |format|
        format.html{ render nothing: true}
        format.js 
      end
    end
  end

  def search_models
    if !params[:fipe_id].blank?
      @car_models = CarModel.where(car_mark_id: CarMark.find_by(fipe_id: params[:fipe_id]).id).select("car_models.fipe_id as id, car_models.name as name")
      respond_to do |format|
        format.html {render nothing: true}
        format.json { render json: { 'object': @car_models }}
      end
    end
  end

  def search_model_years
    if !params[:car_model_fipe_id].blank? && !params[:car_mark_fipe_id].blank?
      @car_model_years = CarModelYear.where(car_model_id: CarModel.find_by(fipe_id: params[:car_model_fipe_id]).id).select("car_model_years.fipe_key as id, car_model_years.name as name")
      respond_to do |format|
        format.html {render nothing: true}
        format.json { render json: { 'object': @car_model_years }}
      end
    end
  end


  private

  def vehicle_price_empty?
    if !params[:car_model][:fipe_id].blank? && !params[:car_model_year][:fipe_id].blank?
      VehiclePrice.where(car_model_year: CarModelYear.find_by(fipe_key: "#{params[:car_model_year][:fipe_id]}-1", car_model: CarModel.find_by(fipe_id: params[:car_model][:fipe_id]))).blank?
    end
  end

  def car_model_year_empty?
    if !params[:car_model_fipe_id].blank?
      CarModelYear.where(car_model: CarModel.find_by(fipe_id: params[:car_model_fipe_id])).blank?
    end
  end

  def car_model_empty?
    if !params[:fipe_id].blank?
      CarModel.where(car_mark: CarMark.find_by(fipe_id: params[:fipe_id])).blank?
    end
  end

  def car_mark_empty?
    CarMark.all.blank?
  end

  def json_uri(url)
    uri = URI(url)
    response = Net::HTTP.get_response(uri)
    if response.is_a?(Net::HTTPSuccess)
      JSON.parse response.body 
    end
  end

  def json_vehicle_price
    json = json_uri("http://fipeapi.appspot.com/api/1/carros/veiculo/#{params[:car_mark][:fipe_id]}/#{params[:car_model][:fipe_id]}/#{params[:car_model_year][:fipe_id]}-1.json")
    VehiclePrice.create(
      name: json['name'],
      price: json['preco'],
      year_model: json['ano_modelo'],
      fuel: json['combustivel'],
      reference: json['referencia'],
      mark: json['marca'],
      car_model_year: CarModelYear.find_by(fipe_key: "#{params[:car_model_year][:fipe_id]}-1", car_model: CarModel.find_by(fipe_id: params[:car_model][:fipe_id]))
    )
  end
  def json_model_year
    json = json_uri("http://fipeapi.appspot.com/api/1/carros/veiculo/#{params[:car_mark_fipe_id]}/#{params[:car_model_fipe_id]}.json")
    json.each do |model_year|
      CarModelYear.create(
        name: model_year["name"], 
        fipe_key: model_year['key'],
        car_model: CarModel.find_by(fipe_id: params[:car_model_fipe_id])
      )
    end    
  end

  def json_model
    json = json_uri("http://fipeapi.appspot.com/api/1/carros/veiculos/#{params[:fipe_id]}.json")
    json.each do |model|
      CarModel.create(
        name: model["name"], 
        fipe_name: model['fipe_name'], 
        fipe_key: model['key'],
        fipe_id: model["id"], 
        car_mark: CarMark.find_by(fipe_id: params[:fipe_id])
      )
    end
  end

  def json_mark
    json = json_uri("http://fipeapi.appspot.com/api/1/carros/marcas.json")
    json.each do |mark|
      CarMark.create(
        name: mark["name"], 
        fipe_name: mark['fipe_name'], 
        fipe_key: mark['key'],
        fipe_id: mark["id"]
      )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_index.html.erb
<% if !@vehicle_prices.blank?%>
	<div class="col-lg-12">
		<div class="col-lg-12">
			<label>Mês de referência</label>: <%=@vehicle_prices.reference%>
		</div>	
		<div class="col-lg-12">
			<label>Marca</label>: <%=@vehicle_prices.mark%>
		</div>	
		<div class="col-lg-12">
			<label> Modelo</label>: <%=@vehicle_prices.name%>
		</div>
		<div class="col-lg-12">
			<label>Ano/Modelo</label>: <%=(@vehicle_prices.year_model == '32000' ? 'Zero KM': @vehicle_prices.year_model) %>
		</div>
		<div class="col-lg-12">
			<label> Combustível</label>: <%=@vehicle_prices.fuel%>
		</div>
		<div class="col-lg-12">
			<label> Preço</label>: <%=@vehicle_prices.price%>
		</div>
	</div>
<% end %>

app/views/home/index.html.erb
<%= form_tag search_vehicle_prices_home_index_path, remote: true, method: :get do %>
	<div class="col-lg-12 well">
		<div class="col-lg-4 form-space">
		<%= label_tag "fipe_id", "Marcas de Veículos" %>
		<%= select 'car_mark', 'fipe_id', @car_marks.collect{|mark| [mark.name, mark.id]}, {prompt: 'Selecione uma marca'}, class: 'form-control' %>
		</div>
		<div id="car_models_id" class="col-lg-4 form-space">
		<%= label_tag "fipe_id", "Modelos de Veículos" %>
		<%= select 'car_model', 'fipe_id', [], {prompt: 'Selecione um Modelo'}, class: 'form-control', disabled: true %>
		</div>
		<div id="car_model_years_id" class="col-lg-4 form-space">
		<%= label_tag "fipe_id", "Ano/Modelo" %>
		<%= select 'car_model_year', 'fipe_id', [], {prompt: 'Selecione um Ano/Modelo'}, class: 'form-control', disabled: true %>
		</div>	

		<div class="col-lg-12 form-space">
			<%= label_tag "" %>
			<%= submit_tag 'Filtrar', class: 'btn btn-default' %>
		</div>
	</div>
<% end%>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"></h3>
  </div>
  <div class="panel-body">
		<div id="show_price">
			<%= render 'index'%>
		</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdtsysApplicantTest</title>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="overlay-body">
		<%= yield %>
	</div>
  <div class="loader">
    <div class="loader__figure"></div>
    <p class="loader__label"></p>    
  </div>	
</body>
</html>